
'use client';

import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { verifyReportAuthenticity } from '@/ai/flows/verify-report-authenticity';
import { Bar, BarChart, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { cn } from '@/lib/utils';
import { ShieldCheck, Info } from 'lucide-react';

type AuthenticityDetailsDialogProps = {
  text: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

export function AuthenticityDetailsDialog({ text, open, onOpenChange }: AuthenticityDetailsDialogProps) {
  const [authenticityScore, setAuthenticityScore] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (open && text) {
      setLoading(true);
      async function getAuthenticity() {
        try {
          const result = await verifyReportAuthenticity({ text });
          setAuthenticityScore(result.authenticityScore);
        } catch (e) {
          console.error("Failed to verify authenticity:", e);
          setAuthenticityScore(0.5); // Fallback score
        } finally {
          setLoading(false);
        }
      }
      getAuthenticity();
    }
  }, [open, text]);

  const getAuthenticityColor = (score: number | null) => {
    if (score === null) return 'bg-gray-400';
    if (score > 0.75) return 'bg-green-500';
    if (score > 0.5) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  const getVerdict = (score: number | null) => {
    if (score === null) return 'Analyzing...';
    if (score > 0.75) return 'Likely Authentic';
    if (score > 0.5) return 'Potentially Authentic';
    if (score > 0.25) return 'Potentially Misleading';
    return 'Likely Misleading';
  };

  const score = authenticityScore ?? 0;
  const chartData = [
    { name: 'Authenticity', score: score * 100, fill: 'hsl(var(--primary))' },
  ];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Authenticity Analysis</DialogTitle>
          <DialogDescription>
            AI-powered analysis to determine the authenticity of the report.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4">
          {loading ? (
            <div className="space-y-4">
              <Skeleton className="h-8 w-1/2" />
              <Skeleton className="h-4 w-1/4" />
              <Skeleton className="h-40 w-full" />
            </div>
          ) : (
            <div className="space-y-4">
                <div className="flex items-center gap-2">
                    <ShieldCheck className={cn("h-6 w-6", getAuthenticityColor(authenticityScore).replace('bg-', 'text-'))} />
                    <h3 className="text-xl font-bold">{getVerdict(authenticityScore)}</h3>
                </div>
                <p className="text-4xl font-bold">
                    {Math.round(score * 100)}%
                    <span className="text-lg font-normal text-muted-foreground"> Authentic</span>
                </p>

                <div className="h-40 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={chartData} layout="vertical" margin={{ left: 10, right: 10 }}>
                            <CartesianGrid strokeDasharray="3 3" horizontal={false} />
                            <XAxis type="number" domain={[0, 100]} tickFormatter={(tick) => `${tick}%`} />
                            <YAxis type="category" dataKey="name" hide />
                            <Tooltip
                                cursor={{ fill: 'hsl(var(--accent))' }}
                                contentStyle={{
                                    background: 'hsl(var(--background))',
                                    border: '1px solid hsl(var(--border))',
                                    borderRadius: 'var(--radius)',
                                }}
                                labelStyle={{ fontWeight: 'bold' }}
                                formatter={(value: number) => [`${value.toFixed(2)}%`, 'Score']}
                            />
                            <Bar dataKey="score" barSize={30} radius={[0, 4, 4, 0]} />
                        </BarChart>
                    </ResponsiveContainer>
                </div>

                <div className="flex items-start gap-2 bg-secondary/50 p-3 rounded-lg">
                    <Info className="h-4 w-4 mt-1 text-muted-foreground flex-shrink-0" />
                    <p className="text-xs text-muted-foreground">
                        This score is generated by an AI model and is not a guarantee of authenticity. Always consider the source and context.
                    </p>
                </div>
            </div>
          )}
        </div>
        <DialogFooter>
          <Button onClick={() => onOpenChange(false)}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
